// Generates lib/firebase_options.dart from environment variables (Vercel CI).
// Required env: FIREBASE_API_KEY, FIREBASE_APP_ID, FIREBASE_MESSAGING_SENDER_ID,
//               FIREBASE_PROJECT_ID, FIREBASE_AUTH_DOMAIN, FIREBASE_STORAGE_BUCKET
// Optional: FIREBASE_IOS_BUNDLE_ID (default com.aerofit.aerofit)

import 'dart:io';

void main() {
  final required = [
    'FIREBASE_API_KEY',
    'FIREBASE_APP_ID',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_STORAGE_BUCKET',
  ];

  for (final key in required) {
    if (Platform.environment[key]?.isNotEmpty != true) {
      stderr.writeln('Missing env: $key');
      exit(1);
    }
  }

  final apiKey = _env('FIREBASE_API_KEY');
  final appId = _env('FIREBASE_APP_ID');
  final senderId = _env('FIREBASE_MESSAGING_SENDER_ID');
  final projectId = _env('FIREBASE_PROJECT_ID');
  final authDomain = _env('FIREBASE_AUTH_DOMAIN');
  final storageBucket = _env('FIREBASE_STORAGE_BUCKET');
  final iosBundleId =
      Platform.environment['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.aerofit.aerofit';

  final content = '''
// GENERATED by tool/generate_firebase_options.dart — do not edit on CI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('Platform not configured.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '$apiKey',
    appId: '$appId',
    messagingSenderId: '$senderId',
    projectId: '$projectId',
    authDomain: '$authDomain',
    storageBucket: '$storageBucket',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$apiKey',
    appId: '$appId',
    messagingSenderId: '$senderId',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '$apiKey',
    appId: '$appId',
    messagingSenderId: '$senderId',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
    iosBundleId: '$iosBundleId',
  );

  static const FirebaseOptions macos = ios;
  static const FirebaseOptions windows = web;

  static bool get isConfigured => apiKey.isNotEmpty && apiKey != 'REPLACE_ME';
}
''';

  File('lib/firebase_options.dart').writeAsStringSync(content);
  stdout.writeln('Wrote lib/firebase_options.dart');
}

String _env(String key) => Platform.environment[key]!.replaceAll("'", "\\'");
